### ISSUE TITLE
Getting Angular to do what I want

### ISSUE THREAD

**Issue by supernoir** [supernoir/binary-search-game#3]
I was hoping I could have a working prototype for the first Rubynette meeting in 2016, but I need a little hint to get it to work... @stefanwille, could you help me out?
### What kinda works:
- user number (the number that the computer is supposed to figure out) can be entered by user, is displayed, is validated and is being passed throughout the scope of the mainCtrl (well... mostly)
- The basic run-through works, as in reporting the current operating Range, the calculation of the middle value of the range and the user prompt (= askQuestion)
- User can click on two buttons (up/down; ng-click triggers the respective function) in theory, this should set the value of the question variable to the value of the current highest or lowest. With this information, the binarySearch function should be able to run and output the next step. I could either let it be displayed in a new bootstrap container, or use the previous container (which would be even sleeker, we aka the user only need to see the current one anyways, right?)
### What doesn't work:
- The very first cycle shouldn't even be displayed... The user doesn't care about 100 - 0 = 100.
- The user triggered cycle ends in NaN variable values... I am kinda lost why this happens. I think it means that the variables are either set back to NaN because the goDown/goUp functions aren't accessing the scope variables OR the variables aren't being passed to this function at all for some other reason I haven't been thinking of.
- I haven't implemented a win state
- etc etc etc

**Comment by stefanwille** [comment]
Ok, here we go:
- You ask the user for a number between 0 and 100, but your probably want a number between 1 and 100, so that the interval (0, 101) so that its boundary values do not include allowed values on both ends.
- To suppress the first cycle, you can test for the step number and and display the calculactions only for step number > 1. For instance,

```
  middle = $scope.calculateMiddle(lowest,highest);
  if(step > 1) {
    $scope.displayMiddle(middle)
  }
```

For this you need to split $scope.calculateMiddle into two functions - one that calculates (calculateMiddle) and one that displays (displayMiddle).
- To find out where your numbers go wrong, I recommend that you add console.log statements and check the output in the JavaScript console (ALT-CMD-J in Chrome). Like this:

```
$scope.calculateMiddle  = function(lowest,highest){
    console.log("calculateMiddle - lowest", lowest, "highest", highest);
    middle = highest - lowest;
    console.log("calculateMiddle - middle", middle);
    document.getElementById("middle").innerHTML = "The middle value is " + highest + " - " + lowest + " = " + middle;
    return $scope.middle;
}

```

This is a classic debugging technique that was used by generations of developers! Well, there were not that many generations, but it's still true.

Or you can use the debugger from the Chrome developer tools (CMD+J). If you don't know how to use the debugger than read a tutorial or wait until tonight so that I can show you.

Both techniques are super valuable to learn!!!

**Comment by supernoir** [comment]
Thank you this was super helpful! :) :) :)
